version: '3.4'

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: